server:
  port: 8762

spring:
  application:
    name: eureka-server-2

eureka:
  instance:
    hostname: localhost
  client:
    #registerWithEureka: false
    #fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
