server:
  port: 8888

spring:
  application:
    name: zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/


zuul:
  routes:
    api-user:
      path: /user/**
      serviceId: microservice-provider-user
    api-movie:
          path: /movie/**
          serviceId: microservice-consumer-movie